#!/usr/bin/env python3
"""Generate fixed C++/CMake registry fragments for validated API plugins."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from plugin_catalog import DEFAULT_PLUGIN_ROOT, PluginCatalogError, discover_plugins


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _cpp(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def generate(plugin_root: Path, out: Path) -> dict[str, Any]:
    records = discover_plugins(plugin_root)
    headers = sorted({header for record in records for header in record.manifest["sdk_headers"]})
    modules = sorted({module for record in records for module in record.manifest["sdk_modules"]})

    _write(
        out / "generated_plugin_headers.inc",
        "// Generated by generate_plugin_registry.py; do not edit.\n"
        + "".join(f"#include <{header}>\n" for header in headers),
    )
    adapter_lines = ["// Generated by generate_plugin_registry.py; do not edit.\n"]
    entry_lines = ["// Generated by generate_plugin_registry.py; do not edit.\n"]
    metadata_lines = [
        "// Generated by generate_plugin_registry.py; do not edit.\n",
        "const std::map<std::string, std::string>& GeneratedPluginManifestHashes()\n",
        "{\n",
        "    static const std::map<std::string, std::string> values = {\n",
    ]
    versions_lines = [
        "const std::map<std::string, int>& GeneratedPluginVersions()\n",
        "{\n",
        "    static const std::map<std::string, int> values = {\n",
    ]
    contracts_lines = [
        "const std::map<std::string, int>& GeneratedPluginContractVersions()\n",
        "{\n",
        "    static const std::map<std::string, int> values = {\n",
    ]
    for record in records:
        relative_adapter = record.adapter_path.relative_to(plugin_root.parent).as_posix()
        adapter_lines.append(f'#include "{relative_adapter}"\n')
        entry_lines.append(f'        {{{_cpp(record.api)}, &{record.manifest["adapter_symbol"]}}},\n')
        metadata_lines.append(
            f'        {{{_cpp(record.api)}, {_cpp(record.manifest_sha256)}}},\n'
        )
        versions_lines.append(
            f'        {{{_cpp(record.api)}, {int(record.manifest["version"])}}},\n'
        )
        contracts_lines.append(
            f'        {{{_cpp(record.api)}, {int(record.manifest["contract_version"])}}},\n'
        )
    metadata_lines.extend(["    };\n", "    return values;\n", "}\n"])
    versions_lines.extend(["    };\n", "    return values;\n", "}\n"])
    contracts_lines.extend(["    };\n", "    return values;\n", "}\n"])
    _write(out / "generated_plugin_adapters.inc", "".join(adapter_lines))
    _write(out / "generated_plugin_entries.inc", "".join(entry_lines))
    _write(
        out / "generated_plugin_metadata.inc",
        "".join(metadata_lines + versions_lines + contracts_lines),
    )
    _write(
        out / "generated_plugins.cmake",
        "# Generated by generate_plugin_registry.py; do not edit.\n"
        "set(SGGK_PLUGIN_LIBRARIES\n"
        + "".join(f"    SGGK_{module}\n" for module in modules)
        + ")\n",
    )
    index = {
        "schema_version": 1,
        "plugin_count": len(records),
        "plugins": [record.as_dict() for record in records],
        "sdk_headers": headers,
        "sdk_modules": modules,
    }
    _write(out / "plugin_index.json", json.dumps(index, indent=2, ensure_ascii=False) + "\n")
    return index


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plugin-root", default=str(DEFAULT_PLUGIN_ROOT))
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    try:
        index = generate(Path(args.plugin_root).resolve(), Path(args.out).resolve())
    except (OSError, ValueError, PluginCatalogError, json.JSONDecodeError) as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False))
        return 2
    print(json.dumps({"ok": True, **index}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
